### ISSUE TITLE
Setting the Activity value to the Time Entry does not work

### ISSUE THREAD

**Issue by koren85** [anteo/redmine_custom_workflows#126]
Hello!
I have a question about how to assign a value for the Activity field in the TimeEntry before saving, without manually selecting the value. I use the following code in the block before saving to pass the value to the Activity field: 
if Group.find (88) .users.include? User.current
    @ time_entry.activity_id = 10
end
But when saving, a message appears indicating that no value has been selected for the activity field. After manual selection and subsequent saving, the code works and the value 10 is written in the field. What am I doing wrong? I will be glad to any help! Thank you in advance!

**Comment by picman** [comment]
So the time entry is correctly filled in and you just changing the activity_id if the current user belongs to the particular group, right?
Check the `production.log` and post the related lines.

**Comment by koren85** [comment]
With this code I want to predetermine the value of the field and save the user from manually filling it

**Comment by AirTibu** [comment]
Hi,

If you catched the Activity ID from the hyperlink of activity enumeration, then it caused the problem, because it is contains the parent_id of enumeration and NOT the right, project specific enumeration id:

![image](https://user-images.githubusercontent.com/68789735/90345462-09223200-e021-11ea-90d9-18c9dff299e9.png)
