### ISSUE TITLE
Create new issue in another project when closed main issue

### ISSUE THREAD

**Issue by Bezvastudio** [anteo/redmine_custom_workflows#137]
Hi,
after completing one issue, I would need to create a new issue in another project. And now I have 2 problems: 
1. I cannot create a new issue from a closed issue
1. I cannot create a new issue in another project

I tried the following code
before save
 ```ruby
@need_create = status_id_changed? && !new_record? && status_id==5
```
after save
```ruby
if @need_create
  issue = Issue.new(
    :author => User.current,
    :project_id => grafika4marketing,
    :tracker => tracker,
    :assigned_to => author,
    :subject => subject+" Generated",
    :description => "Description"
    )
  issue.save!
end
```
Status id 5 is Closed status
It works if I create a new issue in the same project and in an open status

**Comment by picman** [comment]
1) If it fails, what does say the `production.log` then? Maybe you are just not allowed to create issues in the another project or something like that. It should be written in the `production.log` as `save!` should throws an exception in case of a failure.
2) I thing that a better approach to create object is as follow instead of using constructors with a list of parameters.

```ruby
issue = Issue.new
issue.subject = 'xxx'
issue.project_id = 36
...
issue.save!
```

**Comment by Bezvastudio** [comment]
So the mistake was trivial. In project_id I wrote its identifier, not a numeric ID. 
If I use `:project_id => 12`,then everything works correctly.
And the second mistake was also quite clear. If I create a subtask, it cannot be created from a task that is closed. Because the parental task cannot be closed unless the sub-task is completed.

Thank you for your quick help.
