### ISSUE TITLE
can i change the ID For issue

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#176]
can i change ticket ID BECUASE its sequence
and but it depend in custom.feld value like that if cfs[10]=20 the ID change to =20
and make sure the ID uniqe

**Comment by AirTibu** [comment]
Honestly speaking, to change the issue ID is strictly not recommended, because it is protected primary key and has several other functions.

Much more friendly solution, if you create an custom field (lets call 'Ticket ID') and you change this field. 
In this case, you can use this code in BEFORE SAVE section:

```
if self.custom_field_value(10).present? && CustomValue.where(:custom_field_id => '184').pluck(:value).include?(self.custom_field_value(10)) && self.custom_field_value(10) != self.custom_value_for(10).try(&:value)
  errors.add(:base,"This Ticket ID is already exist!")
else
  self.custom_field_values = { 184 => @issue.custom_field_value(9).to_i}
end
```

Change the number 184 to your new Ticket ID custom field id. The number 10 is represent your cfs[10] custom field. (Both custom field format should be integer.)

I hope this helps!
