### ISSUE TITLE
Option to configure which trackers can be set as subtasks for each tracker

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#186]
hi all
how i can configure when i added subtask
if Tracker 1 just only  available subtask Tracker 10 and Tracker 11( hide all trackers)
if Tracker 2  just only  available subtask Tracker 12 and Tracker 13 (hide all trackers)

**Comment by AirTibu** [comment]
Hi,

Honestly speaking, this is good question. Most probably there are a plugin somewhere, which able to manage it.

Without plugin, I have 2 idea, which is not so nice, but could works:

**Example 1:**
Your tracker 1 default status is "In progress"

Create to another status, like:

**"Create Tracker 10"**
**"Create Tracker 11"**

**_Note: for simplicity, the status_id should be 10 and 11, but don't forget to rewrite it correctly!_**

If the user would like to add a subtask, then they have to change the status from "In progress" to **"Create Tracker 10"**

You can use the well known code from "Example workflows"
https://github.com/anteo/redmine_custom_workflows/wiki/Example-Workflows

**# = before_save = #**
@create_subtask_tracker_10 = status_id_changed? &&  status_id==10
@create_subtask_tracker_11 = status_id_changed? &&  status_id==11

**# = after_save = #**
if @create_subtask_tracker_10
  issue = Issue.create!(
    :project => project,
    :tracker_id => '10',
    :parent_issue_id => id,
    :subject => "Subtask in tracker 10")
end

if @create_subtask_tracker_11
  issue = Issue.create!(
    :project => project,
    :tracker_id => '11',
    :parent_issue_id => id,
    :subject => "Subtask in tracker 11")
end

**Example 2:**

Maybe you can use API. Create a formatable text field, and add the right API URL to create a new subtask.

IMPORTANT:
In both cases you should make the parent_id field to READ_ONLY in workflow. This ensure, that the users cannot add subtasks, just only via status change solution. (minimum 1 of the role should be with rights to change the parent_id, because if all role restrict the parent_id, then your program code cannot change it. Usually I have a specific role for such issues.)

I hope it's help!

**Comment by ashrafalzyoud** [comment]
Thank you for the quick response and your cooperation
But my goal of the question Facilitate selection
 becasue i have alot of  main trackers and subtask trackers
if user chose tracker 1 THIS only allow for him add subtask ( tracker 10,11)
if choose tracker 2 THIS only allow for him add subtask ( tracker 12.13)

**Comment by AirTibu** [comment]
Hi,

I think so, you should find a plugin for that purpose. Check this plugin:

https://www.redmine.org/plugins/redmine_issue_templates

https://github.com/akiko-pusu/redmine_issue_templates/wiki

It is not exactly the same, what you want, but it's working similar, maybe with some creativity, you can adopt into your solution.

**Comment by ashrafalzyoud** [comment]
1
